version: '3'

services:
  ukbc_api_server:
    image: robbrad182/uk-bin-collection:latest
    ports:
      - "8080:8080"  # Adjust the ports as needed
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
