name: Test Councils (Nightly Full Run)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Nightly schedule for full test run

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry==1.8.4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: make install-dev

      - name: Lint JSON
        run: jq empty uk_bin_collection/tests/input.json

      - name: Set Council Tests Environment Variable
        id: set-council-tests
        run: |
          COUNCIL_TESTS=""
          echo "council_tests=$COUNCIL_TESTS" >> $GITHUB_OUTPUT

    outputs:
      council_tests: ${{ steps.set-council-tests.outputs.council_tests }}

  unit-tests:
    name: Run Unit Tests
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
        poetry-version: [1.8.4]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry==${{ matrix.poetry-version }}

      - name: Install Dependencies
        run: make install-dev

      - name: Run Unit Tests
        run: make unit-tests

      - name: Upload Test Results to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml

  parity-check:
    name: Parity Check
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
        poetry-version: [1.8.4]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry==${{ matrix.poetry-version }}

      - name: Install Dependencies
        run: make install-dev

      - name: Check Parity of Councils / input.json / Feature file
        run: |
          repo=${{ github.event.pull_request.head.repo.full_name || 'robbrad/UKBinCollectionData' }}
          branch=${{ github.event.pull_request.head.ref || 'master' }}
          make parity-check repo=$repo branch=$branch

  integration-tests:
    name: Run Integration Tests
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
        poetry-version: [1.8.4]
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2gb --name selenium --hostname selenium
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: pipx install poetry==${{ matrix.poetry-version }}

      - name: Install Dependencies
        run: make install-dev

      - name: Run Integration Tests
        env:
          HEADLESS: True
          COUNCIL_TESTS: ${{ needs.setup.outputs.council_tests }}
        run: make matrix=${{ matrix.python-version }} councils="${{ env.COUNCIL_TESTS }}" integration-tests
        continue-on-error: true

      - name: Archive Integration Tests Results
        uses: actions/upload-artifact@v4
        with:
          name: integration-tests-results-${{ matrix.python-version }}
          path: build/${{ matrix.python-version }}/allure-results
        
  # Only generate and upload Allure reports on schedule
  report:
    name: Generate and Upload Reports
    needs: [unit-tests, parity-check, integration-tests]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:

      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: integration-tests-results-${{ matrix.python-version }}
          path: build/${{ matrix.python-version }}/allure-results

      # Fetch Allure history for the full report (optional)
      - name: Get Allure history - Full Report
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      # Generate Allure Reports (Full)
      - name: Allure report action for Full Run
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: build/${{ matrix.python-version }}/allure-results
          subfolder: ${{ matrix.python-version }}/full
          allure_history: allure-history-full
          keep_reports: 20

      # Archive the Full Report
      - name: Tar full report
        run: tar -cvf allure_full_history_${{ matrix.python-version }}.tar allure-history-full/${{ matrix.python-version }}/full

      # Upload the Full Report artifact
      - name: Upload artifact for Full Report
        uses: actions/upload-artifact@v4
        with:
          name: allure_full_history_${{ matrix.python-version }}
          path: allure_full_history_${{ matrix.python-version }}.tar

  # Deploy only on schedule + master branch
  deploy:
    name: Deploy Reports
    runs-on: ubuntu-latest
    permissions:
      contents: write
  
    needs: report
    steps:
      # Checkout the repository to work with the git history
      - name: Checkout repository
        uses: actions/checkout@v4
  
      # Download Full Artifacts
      - uses: actions/download-artifact@v4
        name: Download Full Artifacts
        with:
          name: allure_full_history_3.12
          path: allure-history/tars
  
      - name: Display structure of downloaded files
        run: ls -R
  
      - name: Display directory
        run: pwd
  
      # Untar reports into a temporary directory
      - name: Untar reports to temporary directory
        run: |
          mkdir -p temp_extracted  # Create a temporary directory for untarring
          for i in allure-history/tars/*.tar; do
            tar -xvf "$i" -C temp_extracted  # Untar into the temporary directory
          done
  
      # Move the files from the correct location and delete unnecessary folders
      - name: Move files to the correct location
        run: |
          mkdir -p 3.12/full  # Ensure the target directory exists
          mv temp_extracted/allure-history-full/3.12/full/* 3.12/full/  # Move files to the target directory
          rm -rf temp_extracted  # Clean up the temporary extraction folder
  
      # Remove the tar reports
      - name: Remove tar reports
        run: rm -rf allure-history/tars
  
      # Display structure after untarring and moving
      - name: Display structure of moved files
        run: ls -R
  
      # Set up Git for pushing changes
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      # Authenticate using the personal access token (GH_PAGES_TOKEN)
      - name: Authenticate with GH_PAGES_TOKEN
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository }}.git
      
      # Pull the latest changes from gh-pages and switch to the gh-pages branch
      - name: Pull latest changes from gh-pages
        run: |
          git fetch origin
          git checkout gh-pages
          git pull origin gh-pages
    
      # Commit and push changes to gh-pages
      - name: Commit and push changes to gh-pages
        run: |
          git add .
          git commit -m "Deploy reports to gh-pages"
          git push origin gh-pages
