name: Deploy Wiki

on:
  push:
    # Trigger only when wiki directory changes
    paths:
      - "wiki/**"
      - "uk_bin_collection/tests/input.json"
    branches: [ "master" ]
  pull_request:
    # Trigger only when wiki directory changes
    paths:
      - "wiki/**"
      - "uk_bin_collection/tests/input.json"
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  deploy-wiki:
    # Only run on main branch push (e.g. after pull request merge).
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: wiki
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Run image
      uses: abatilo/actions-poetry@v3.0.1
      with:
        poetry-version: '1.8.4'

    - name: Install
      run: make install

    - name: Update Councils.md from input.json
      run: make update-wiki

    - name: Commit and Push Wiki changes
      run: |
        git config --global user.name "Wiki GitHub Action"
        git config --global user.email "action@github.com"
        git add wiki
        git commit -m "docs: Update Councils.md from input.json"
        git push
      continue-on-error: true

    - name: Deploy Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v4
      with:
        # Make sure WIKI_DIR ends with / as action uses rsync
        path: wiki/
        ignore: "generate_wiki.py"
