name: Deploy Wiki

on:
  push:
    # Trigger only when wiki directory changes
    paths:
      - "wiki/**"
    branches: [ "master" ]
  pull_request:
    # Trigger only when wiki directory changes
    paths:
      - "wiki/**"
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    environment: wiki
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run image
      uses: abatilo/actions-poetry@v2.3.0
      with:
        poetry-version: '1.2.1'

    - name: Install
      run: make install

    - name: Update Councils.md from input.json
      run: make update-wiki

    - name: Commit and Push Wiki changes
      run: |
        git config --global user.name "Wiki GitHub Action"
        git config --global user.email "action@github.com"
        git add wiki
        git commit -m "Update Councils.md from input.json"
        git push

    - name: Deploy Wiki Changes
      uses: Andrew-Chen-Wang/github-wiki-action@v3
      env:
        # Make sure WIKI_DIR ends with / as action uses rsync
        WIKI_DIR: wiki/
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_MAIL: ${{ secrets.YOUR_EMAIL }}
        GH_NAME: ${{ github.repository_owner }}
        EXCLUDED_FILES: "generate_wiki.py"
